# Generated by Django 5.2.3 on 2025-08-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_urls',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
