# Generated by Django 5.2.3 on 2025-08-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.AddField(
            model_name='post',
            name='image_3d',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='example-slug', unique=True),
            preserve_default=False,
        ),
    ]
