# Generated by Django 5.2.3 on 2025-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=' eample-slug', unique=True),
            preserve_default=False,
        ),
    ]
